export { default as headerPhoto } from './images/header-pic.webp'
export { default as asx } from './images/site-mock.webp'
export { default as maven } from './images/mock-site3.webp'
export { default as chatPhoto } from './images/chat-img.webp'
export { default as elementicaHomePage } from './images/elementica.webp'
export { default as imtHomePage } from './images/imt.webp'
export { default as udemyHomePage } from './images/udemy.webp'
export {default as chowWow} from './images/chow-wow.png'
export {default as chowWowFirst} from './images/chow-wow-1.png'
export {default as chowWowSecond} from './images/chow-wow-2.png'
export {default as betwie} from './images/betwie.png'
export {default as betwieFirst} from './images/betwie-1.png'
export {default as betwieSecond} from './images/betwie-2.png'
export {default as tradingBot} from './images/trading-bot.webp'

export { default as soundSendMessage } from './sounds/telegram-sound-send.mp3'
export { default as soundResponseMessage } from './sounds/telegram-sound-response.mp3'
